import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  docs: {
    Changelog: [
      {
        type: 'doc',
        id: 'changelog',
      },
    ],
    // Add other sections as needed
  },
};

export default sidebars;
